Change tests to reference demo website
browserstack/mocha-browserstack pull request #3
Opened 2022-02-02 23:44 UTC by emalysz

See https://browserstack.atlassian.net/browse/DOC-2?focusedCommentId=304255

2022-02-02 23:49 UTC, emalysz commented
@francisf

2022-02-03 16:26 UTC, francisf requested changes

2022-02-03 16:26 UTC, francisf commented on specs/parallel_test.js
> +                      driver.quit().then(function() {
this should be in finally block?  +

done() in single_test.js

2022-02-03 16:26 UTC, francisf commented on specs/parallel_test.js
> +                      await driver.executeScript(
can we use await everywhere (vs promises - then) + in single_test.js

2022-02-03 16:26 UTC, francisf commented on conf/parallel.conf.js
> +      'os': 'Windows',
minor nitpick here and for other caps.. keep os and os_version keys next to each other.

2022-02-04 17:02 UTC, emalysz commented
@francisf committed some changes to the branch

2022-02-04 18:08 UTC, francisf approved these changes

2022-02-04 18:08 UTC, merged